strategy: FedAvg
dataset: har
model: tabnet
alpha: 100
seed: 1

batch_size: 256
rounds: 20

# At the moment, we are assuming that all the clients can always connect.
data_split: [ 16,16,16,16,16,16 ]

metrics:
  - F1Score
  - WeightedF1Score
  - MCC